#!/usr/bin/env bash

mkdir -p "$HOME/.local/bin" # TODO Check to see if it is in the path

if [ ! -f "$HOME/quicklisp/setup.lisp" ]; then
  echo "Installing Quicklisp..."
  tmpfile=$(mktemp)
  curl -fsLo $tmpfile https://beta.quicklisp.org/quicklisp.lisp
  clasp --non-interactive --load $tmpfile --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))"
  rm $tmpfile
elif [ ! -f "$HOME/.clasprc" ]; then
  echo "Creating clasprc..."
  clasp --non-interactive --load $HOME/quicklisp/setup.lisp --eval "(ql-util:without-prompting (ql:add-to-init-file))"
fi

echo "Updating Quicklisp..."
clasp --non-interactive --eval "(unless (ql-dist:find-dist \"quickclasp\") (ql-dist:install-dist \"http://quickclasp.thirdlaw.tech/quickclasp.txt\" :prompt nil))" \
      --eval "(ql:update-all-dists :prompt nil)"

if ! [ -f ~/.config/common-lisp/source-registry.conf.d/apptainer.conf ]; then
    echo "The file ~/.config/common-lisp/source-registry.conf.d/apptainer.conf is missing - creating it"
    mkdir -p ~/.config/common-lisp/source-registry.conf.d
    echo "(:tree \"/home/cando/common-lisp/\")" >~/.config/common-lisp/source-registry.conf.d/apptainer.conf
else
    echo "The file ~/.config/common-lisp/source-registry.conf.d/apptainer.conf already exists"
    cat ~/.config/common-lisp/source-registry.conf.d/apptainer.conf
fi

echo "Installing CANDO user features..."
cando --eval "(ql:quickload :cando-jupyter)" \
      --eval "(ql:quickload :spiros)" \
      --eval "(leap:source \"leaprc.protein.ff14SB\")" \
      --eval "(foldamer:load-force-field t)" \
      --eval "(spiros:load-rotamers)" \
      --eval "(ql:quickload :amber-protein)" \
      --eval "(amber-protein:transfer-amber-atom-types-to-foldamer amber-protein:*foldamer*)" \
      --eval "(amber-protein:load-rotamers)" \
      --eval "(cando-jupyter:install :implementation \"apptainer\" :image t)"

echo "HOME = " $HOME
echo "pwd ~ = " `pwd ~`
echo "Following is the contents of ~/.config/common-lisp/source-registry.conf.d/apptainer.conf"
cat ~/.config/common-lisp/source-registry.conf.d/apptainer.conf
echo "Following is the contents of $HOME/.config/common-lisp/source-registry.conf.d/apptainer.conf"
cat $HOME/.config/common-lisp/source-registry.conf.d/apptainer.conf

