#!/usr/bin/env bash

ninja -C build

mkdir -p "$HOME/.local/bin" # TODO Check to see if it is in the path

export CANDO_DATA=$HOME/work/

if [ ! -f "$HOME/quicklisp/setup.lisp" ]; then
  echo "Installing Quicklisp..."
  tmpfile=$(mktemp)
  curl -fsLo $tmpfile https://beta.quicklisp.org/quicklisp.lisp
  clasp --non-interactive --load $tmpfile --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))"
  rm $tmpfile
elif [ ! -f "$HOME/.clasprc" ]; then
  echo "Creating clasprc..."
  clasp --non-interactive --load $HOME/quicklisp/setup.lisp --eval "(ql-util:without-prompting (ql:add-to-init-file))"
fi

echo "Updating Quicklisp..."
clasp --non-interactive --eval "(unless (ql-dist:find-dist \"quickclasp\") (ql-dist:install-dist \"http://quickclasp.thirdlaw.tech/quickclasp.txt\" :prompt nil))" \
      --eval "(ql:update-all-dists :prompt nil)"

#if [ ! -d "~/.config/common-lisp/source-registry.conf.d/" ]; then
#    mkdir -p ~/.config/common-lisp/source-registry.conf.d
#    echo "(:tree \"/home/cando/common-lisp/\")" >~/.config/common-lisp/source-registry.conf.d/apptainer.conf
#fi

echo "Installing CANDO user features..."
cando --eval "(ql:quickload :cando-jupyter)" \
      --eval "(ql:quickload :ngl-clj)" \
      --eval "(ql:quickload :spiros-rotamers)" \
      --eval "(ql:quickload :amber-protein-rotamers)" \
      --eval "(cando-jupyter:install :bin-path \"$HOME/Development/cando/build/boehmprecise/cando\" :implementation \"scando\" :image t)"

#--eval "(ext:start-autocompilation)" \
