(cl:in-package #:common-lisp-user)

(defpackage #:serial
  (:use #:cl)
  (:export #:serializable))


(defpackage #:topology
  (:use #:common-lisp)
  (:nicknames #:ts)
  (:export
   #:make-topology-from-residue
   #:topologyp
   #:constitution-atom-index
   #:atom-name
   #:element
   #:root-map
   #:bonds
   #:trainer-index
   #:to-atom-index
   #:order
   #:children
   #:name
   #:plug-bonds
   #:atom-name
   #:bond-order
   #:plug-bond
   #:root-node
   #:constitution-from-graph
   #:stereo-information
   #:stereoisomer
   #:make-in-plug
   #:make-out-plug
   #:add-plug
   #:plugs
   #:name
   #:configurations
   #:make-constitution-atoms-from-residue
   #:topology-list
   #:property-list
   #:topology
   #:in-plug
   #:has-plug-named
   #:plug-named
   #:has-in-coupling-p
   #:define-topology
   #:constitution
   #:constitution-atoms
   #:stereoisomer-name
   #:stereoisomer-atoms
   #:build-residue-single-name
   #:connect-residues
   #:is-in-plug-name
   #:other-plug-name
   #:find-in-plug
   #:atom-type
   #:joint-template
   #:bonded-joint-template
   #:in-plug-bonded-joint-template
   #:complex-bonded-joint-template
   #:jump-joint-template
   #:in-plug
   #:name
   #:id
   #:source-monomer
   #:target-monomer
   #:source-plug-name
   #:target-plug-name
   #:children
   #:constitution
   #:atom-name
   #:parent
   #:input-stub-joints
   #:plugs
   #:add-child
   #:sibling
   #:aggregate
   #:ordered-monomers

   #:seen-fragment-internals
   #:seen-index
   #:bad-fragment-internals
   #:context-rotamers
   #:merge-context-rotamers
   #:fragment-internals
   #:internal
   #:jump-internal
   #:bonded-internal
   #:complex-bonded-internal
   #:fragments
   #:internals
   #:bond
   #:angle-rad
   #:dihedral-rad
   #:foldamer-monomer-context
   #:save-clusterable-context-rotamers
   #:load-clusterable-context-rotamers
   #:context-rotamers
   #:context-rotamers-map
   #:monomer-context-to-context-rotamers
   #:dump-fragment-internals
   #:index
   #:next-index
   #:bad-geometry-p
   
   #:make-in-plug-bonded-joint-template
   #:make-bonded-joint-template
   #:make-jump-joint-template
   #:make-complex-bonded-joint-template
   #:stereo-information
   #:build-internal-coordinate-joint-template-tree
   #:build-joint-template
   #:extract-prepare-topologys
   #:target-monomer
   #:define-cap
   #:build-molecule
   #:oligomer-space
   #:oligomers
   #:monomer
   #:directional-coupling
   #:out-plug-name
   #:in-plug-name
   #:monomers
   #:couplings
   #:number-of-sequences
   #:current-stereoisomer-name
   #:other-monomer
   #:goto-sequence
   #:monomer-positions
   #:molecule-index
   #:residue-index
   #:residue
   #:copy-externals
   #:ataggregate
   #:atmolecules
   #:atresidues
   #:joints
   #:zero-all-atom-tree-external-coordinates
   #:build-all-atom-tree-external-coordinates
   #:build-atresidue-atom-tree-external-coordinates
   #:oligomer-space-directional-coupling-iterator-factory

   #:make-joint-tree
   #:joint-tree
   #:children
   #:root
   #:atom-id-map
   #:make-assembler
   #:make-oligomer
   #:topologys-in-oligomer-space

   #:in-plug-name-p
   #:out-plug-name-p
   #:coupling-name

   ;;;
   #:update-joint-tree-internal-coordinates
   #:build-all-atom-tree-external-coordinates
   #:define-part
   #:*topology-groups*
   #:restraints

   #:missing-fragment-match
   #:connected-rotamers-map
   #:rotamer-context-connections
   #:make-rotamer-context-connections
   #:set-rotamer-context-connections
   #:get-rotamer-context-connections
   #:map-rotamer-context-connections
   #:rotamer-context-connections-count

   #:oligomer-monomer-name-at-index
   #:oligomer-monomer-name-for-monomer
   #:missing-rotamer-context-connections-count
   #:matched-context-rotamers-summary

   #:fragment-match-key-before-monomer-context-index
   #:fragment-match-key-after-monomer-context-index
   #:missing-fragment-match-key-before-monomer-context-index
   #:missing-fragment-match-key-after-monomer-context-index
   #:monomer-contexts-vector
   #:focus-monomer-name

   #:build-shapes
   #:monomer-shapes
   #:monomer-shape-vector
   #:root-monomer
   #:random-fragment-conformation-index
   #:make-oligomer-shape
   #:build-one-molecule-for-topology
   #:sketch-svg
   #:make-oligomer-space
   #:calculate-number-of-sequences
   #:energy-function
   #:copy-fragment-internals
   #:copy-internal
   #:deg-to-rad
   #:rad-to-deg
   #:radians-add
   #:radians-incf
   #:radians-sub
   #:angle-sub
   #:walk-joint-template
   #:properties
   #:degrees-add
   #:probability
   #:oligomer-force-field-name
   #:oligomer
   #:build-residue-for-isomer
   #:stereoisomer-atom
   #:atom-charge
   #:copy-oligomer
   #:monomer-indices
   #:internals-values
   #:internals-types
   #:constitution-atom-named
   #:constitution-atom-names-with-dihedrals
   #:monomer-topology
   #:calculate-cluster-dihedral-names
   #:cluster-dihedral-names
   #:cluster-dihedral-vector
   #:cluster-dihedral-rad-vector
   #:convert-dihedral-rad-vector-to-xy-vector
   #:build-all-molecules
   #:energy
   #:monomer-context
   #:clusterable-context-rotamers
   #:fill-internals-from-oligomer-shape
   #:monomer-shape-map
   #:in-monomers
   #:out-monomers
   #:fragment-conformation-index
   #:rotor3
   #:translation
   #:monomer-shape
   #:set-to-closest-matching-fragment-conformation-index
   #:coordinates
   #:joint-with-name
   #:residue-properties
   #:merge-clusterable-context-rotamers
   #:foldamer-name
   #:monomer-on-other-side
   #:in-coupling-plug-name
   #:make-shape-info
   #:foldamer
   #:shape-info
   #:shape-key
   #:shape-kind
   #:keys
   #:kind
   #:kind-keys
   #:monomer-shape-build-order
   #:assign-monomer-shapes
   #:make-rotamer-shape-connections
   #:lookup-rotamer-context-connections
   #:lookup-rotamer-shape-connections
   #:out-coupling-plug-names
   #:append-rotamer-shape-connections
   #:bin-dihedral-deg
   #:shape-key-dihedral-name-p
   #:*phi*
   #:*phi-1*
   #:*psi*
   #:*psi-1*
   #:+phi+
   #:+phi-1+
   #:+psi+
   #:+psi-1+
   #:rotamer-indices
   #:make-backbone-rotamer-shape-connections
   #:make-sidechain-rotamer-shape-connections
   #:assign-backbone-allowed-rotamers
   #:assign-backbone-random-rotamer-indices
   #:allowed-rotamer-indices
   #:assign-backbone-shape-keys
   #:focus-monomer
   #:focused-assembler-atresidue
   #:assembler-atresidue
   #:make-focused-assembler
   #:dihedral-info
   #:dihedral-info-atom
   #:dihedral-info-external
   #:plug-name
   #:external-dihedral-name
   #:oligomer-containing-monomer
   #:delta-energy
   #:lookup-rotamers-for-context
   #:monomer-shape-kind
   #:only-other-out-coupling-plug-name
   #:sorted-build-order
   #:adjustment
   #:external-adjustment
   #:internal-adjustment
   #:apply-fragment-internals-to-atresidue
   #:extract-bond-angle-rad-dihedral-rad
   #:fill-joint-internals
   #:make-coordinates-for-assembler
   #:initialize-adjustment
   #:do-adjustment
   #:find-joint-for-atom
   #:adjust-all-atom-tree-external-coordinates
   #:external-adjust
   #:internal-adjust
   #:adjust-internals
   #:radians-limit
   #:degrees-limit
   #:degrees-sub
   #:fill-internals-from-oligomer-shape-and-adjust
   #:build-all-atom-tree-external-coordinates-and-adjust
   #:rotamers-map
   #:orientation
   #:lab-frame
   #:parent-relative-transform
   #:oligomer-monomer-name
   #:lookup-dihedral-cache
   #:lookup-dihedral-cache-monomer-shape
   #:shape-key-values
   #:rotamer
   #:sidechain-rotamer
   #:backbone-rotamer
   #:rotamers
   #:sidechain-rotamers
   #:shape-key-to-index
   #:backbone-rotamers
   #:rotamers-database
   #:context-to-rotamers
   #:backbone-dihedral-cache-deg
   #:sidechain-monomer-stepper
   #:backbone-monomer-stepper
   #:is-oligomer-space-supported
   #:abstract-topology
   #:define-abstract-topology
   #:is-out-plug-name
   #:joint
   #:internal-planar-adjustment))

  
(defpackage #:topology.dag
  (:use #:common-lisp)
  (:nicknames #:tsd)
  (:export
   #:make-topology-from-residue
   #:parse-oligomer-space-labeled-dag
   #:parse-oligomer-space-dag
   #:validate-dag
   ))

(defpackage #:monomer-context
  (:use #:common-lisp)
  (:export
   #:parse-sexp
   #:matches
   #:match-as-symbol
   #:match
   #:match-iterator
   #:copy-specialized))

(defpackage #:topology.graphviz
  (:use #:common-lisp)
  (:nicknames #:topg)
  (:export
   #:nodes
   #:node-label
   #:directed-edges
   #:directed-edge-from
   #:directed-edge-to
   #:directed-edge-label
   #:render-dag
   #:undirected-edges
   #:undirected-edge-from
   #:undirected-edge-to
   #:undirected-edge-label
   #:graph-label
   #:graph-name
   #:render-foldamer-joint-trees
   #:make-graph
   #:node-id
   #:dot-svg-foldamer-joint-trees))


