(k:sources :iclasp
           #~"aggregateNode.cc"
           #~"jointTemplate.cc"
           #~"pointTree.cc"
           #~"bondId.cc"
           #~"bondedJoint.cc"
           #~"chainNode.cc"
           #~"chiDihedrals.cc"
           #~"conformation.cc"
           #~"coordinateCalculators.cc"
           #~"delayedBondedJoint.cc"
           #~"dofType.cc"
           #~"foldTree.cc"
           #~"jump.cc"
           #~"jumpJoint.cc"
           #~"kin_atom.cc"
           #~"kin_rotamer.cc"
           #~"kinematicsPackage.cc"
           #~"monomerBaseNode.cc"
           #~"monomerId.cc"
           #~"monomerNode.cc"
           #~"originJumpJoint.cc"
           #~"ringClosingMonomerNode.cc"
           #~"rootJointInfo.cc"
           #~"rootBondedJoint.cc"
           #~"stub.cc")

