def build(bld):
    for name in [
        'aggregateNode',
        'jointTemplate',
        'pointTree',
        'bondId',
        'bondedJoint',
        'chainNode',
        'chiDihedrals',
        'conformation',
            'coordinateCalculators',
        'delayedBondedJoint',
        'dofType',
        'foldTree',
        'jump',
        'jumpJoint',
        'kin_atom',
        'kin_rotamer',
        'kinematicsPackage',
        'monomerBaseNode',
        'monomerId',
        'monomerNode',
        'originJumpJoint',
        'ringClosingMonomerNode',
        'rootJointInfo',
        'rootBondedJoint',
        'stub'
    ]:
        source(bld,name)

def source(bld,name):
    full_name = name+'.cc'
    node = bld.path.find_node(full_name)
    assert node != None, "Could not find %s/%s" % ( bld.path.abspath(), full_name )
    bld.extensions_source_files.append(node)


