// FINITE_DIFFERENCE_TEST 
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
fak,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
fbk,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
fck,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
fdk,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
fxk,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
fyk,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
fzk,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
fal,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
fbl,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
fcl,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
fdl,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
fxl,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
fyl,
index);
TEST_FORCE( _evaluateEnergyOnly_NONBONDRB,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
fzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
dhakak,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohakbk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohakck,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohakdk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohakxk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
ohakyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohakzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohakal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohakbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohakcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohakdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohakxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohakyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak - delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak + delta2, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohakzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
dhbkbk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohbkck,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohbkdk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohbkxk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
ohbkyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohbkzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohbkal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohbkbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohbkcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohbkdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohbkxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohbkyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk - delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk + delta2, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohbkzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
dhckck,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohckdk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohckxk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
ohckyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohckzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohckal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohckbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohckcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohckdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohckxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohckyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck - delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck + delta2, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohckzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
dhdkdk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
ohdkxk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
ohdkyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohdkzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohdkal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohdkbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohdkcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohdkdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohdkxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohdkyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, -delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, delta2 + dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohdkzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
dhxkxk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
ohxkyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohxkzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohxkal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohxkbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohxkcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohxkdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohxkxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohxkyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, -delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, delta2 + xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohxkzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, zl),
dhykyk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
ohykzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohykal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohykbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohykcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohykdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohykxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohykyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, -delta2 + yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, delta2 + yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohykzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, zl),
dhzkzk,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al + delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al + delta2, bl, cl, dl, xl, yl, zl),
ohzkal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl + delta2, cl, dl, xl, yl, zl),
ohzkbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl + delta2, dl, xl, yl, zl),
ohzkcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, delta2 + dl, xl, yl, zl),
ohzkdl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, delta2 + xl, yl, zl),
ohzkxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, delta2 + yl, zl),
ohzkyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, -delta2 + zk, al, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, delta2 + zk, al, bl, cl, dl, xl, yl, delta2 + zl),
ohzkzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, zl),
dhalal,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl + delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl + delta2, cl, dl, xl, yl, zl),
ohalbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl + delta2, dl, xl, yl, zl),
ohalcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, delta2 + dl, xl, yl, zl),
ohaldl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, delta2 + xl, yl, zl),
ohalxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, delta2 + yl, zl),
ohalyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al - delta2, bl, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al + delta2, bl, cl, dl, xl, yl, delta2 + zl),
ohalzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, zl),
dhblbl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl + delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl + delta2, dl, xl, yl, zl),
ohblcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, delta2 + dl, xl, yl, zl),
ohbldl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, delta2 + xl, yl, zl),
ohblxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, delta2 + yl, zl),
ohblyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl - delta2, cl, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl + delta2, cl, dl, xl, yl, delta2 + zl),
ohblzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, zl),
dhclcl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, delta2 + dl, xl, yl, zl),
ohcldl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, delta2 + xl, yl, zl),
ohclxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, delta2 + yl, zl),
ohclyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl - delta2, dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl + delta2, dl, xl, yl, delta2 + zl),
ohclzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, zl),
dhdldl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, delta2 + xl, yl, zl),
ohdlxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, delta2 + yl, zl),
ohdlyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, -delta2 + dl, xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, delta2 + dl, xl, yl, delta2 + zl),
ohdlzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, zl),
dhxlxl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, delta2 + yl, zl),
ohxlyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, -delta2 + xl, yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, delta2 + xl, yl, delta2 + zl),
ohxlzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, zl),
dhylyl,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, -delta2 + yl, delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, delta2 + yl, delta2 + zl),
ohylzl,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_NONBONDRB, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, -delta2 + zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, zl),
(ak, bk, ck, dk, xk, yk, zk, al, bl, cl, dl, xl, yl, delta2 + zl),
dhzlzl,
index);
