// FINITE_DIFFERENCE_TEST 
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fx1,
index);
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fy1,
index);
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fz1,
index);
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fx2,
index);
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fy2,
index);
TEST_FORCE( _evaluateEnergyOnly_STAPLE,  delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
fz2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhx1x1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx1y1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx1z1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx1x2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx1y2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx1z2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhy1y1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohy1z1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohy1x2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohy1y2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohy1z2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhz1z1,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohz1x2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohz1y2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohz1z2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhx2x2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx2y2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohx2z2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhy2y2,
index);
TEST_OFF_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE,
delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
ohy2z2,
index);
TEST_DIAGONAL_HESSIAN( _evaluateEnergyOnly_STAPLE, delta2*2.0,
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
(ak, bk, ck, dk, xk, yk, zk, ak, bk, ck, dk, xk, yk, zk),
dhz2z2,
index);
