
cando-run:
	$(HOME)/Development/amber16/bin/sander -O -i 01_Min.in -o 01_Min_cando.out -p alanine_cando.top -c alanine_cando.crd

leap-run:
	$(HOME)/Development/amber16/bin/sander -O -i 01_Min.in -o 01_Min_leap.out -p alanine_leap.top -c alanine_leap.crd

leap-run-no-box:
	$(HOME)/Development/amber16/bin/sander -O -i 01_Min.in -o 01_Min_leap_no_box.out -p alanine_leap_no_box.top -c alanine_leap_no_box.crd
