(in-package amber.params)

(defun parse-mass-db (fin)
  (let ((nonbond-db (chem:make-ffnonbond-db)))
    (loop for ol = (read-line fin nil :eof)
       until (= (length ol) 0)
       do (let* ((parts (core:split ol " \t"))
                 (typename (elt parts 0))
                 (mass (elt parts 1))
                 (polarizability (elt parts 2))
                 (nb (chem:make-ffnonbond)))
            (chem:set-type nb (intern typename :keyword))
            (chem:set-mass nb (util:parse-float mass))
            (chem:set-polarizability nb (util:parse-float polarizability))
            (chem:ffnonbond-db-add nonbond-db nb)))
    nonbond-db))
