// SET_EVAL 
 	EVAL_SET(x1, x1);
 	EVAL_SET(y1, y1);
 	EVAL_SET(z1, z1);
 	EVAL_SET(xa, xa);
 	EVAL_SET(ya, ya);
 	EVAL_SET(za, za);
 	EVAL_SET(ka, ka);
 	EVAL_SET(Energy, Energy);
 	EVAL_SET(fx1, fx1);
 	EVAL_SET(fy1, fy1);
 	EVAL_SET(fz1, fz1);
 	EVAL_SET(dhx1x1, dhx1x1);
 	EVAL_SET(dhy1y1, dhy1y1);
 	EVAL_SET(dhz1z1, dhz1z1);
 	EVAL_SET(ohx1y1, ohx1y1);
 	EVAL_SET(ohx1z1, ohx1z1);
 	EVAL_SET(ohy1z1, ohy1z1);
 	EVAL_SET(AnchorDeviation, AnchorDeviation);
 