#if USE_EXPLICIT_DECLARES
// declare variables
DECLARE_FLOAT(plabmx);
DECLARE_FLOAT(plabmy);
DECLARE_FLOAT(plabmz);
DECLARE_FLOAT(tx31);
DECLARE_FLOAT(tx32);
DECLARE_FLOAT(tx33);
DECLARE_FLOAT(tx34);
DECLARE_FLOAT(tx35);
DECLARE_FLOAT(tx36);
DECLARE_FLOAT(tx37);
DECLARE_FLOAT(tx38);
DECLARE_FLOAT(tx39);
DECLARE_FLOAT(tx40);
DECLARE_FLOAT(tx41);
DECLARE_FLOAT(tx42);
DECLARE_FLOAT(tx43);
DECLARE_FLOAT(tx44);
DECLARE_FLOAT(tx45);
DECLARE_FLOAT(tx46);
DECLARE_FLOAT(tx47);
DECLARE_FLOAT(tx48);
DECLARE_FLOAT(tx49);
DECLARE_FLOAT(tx50);
DECLARE_FLOAT(tx51);
DECLARE_FLOAT(tx52);
DECLARE_FLOAT(tx53);
DECLARE_FLOAT(tx54);
DECLARE_FLOAT(tx55);
DECLARE_FLOAT(tx56);
DECLARE_FLOAT(tx57);
DECLARE_FLOAT(tx58);
DECLARE_FLOAT(tx59);
DECLARE_FLOAT(tx60);
DECLARE_FLOAT(tzz61);
DECLARE_FLOAT(tzz62);
DECLARE_FLOAT(tzz63);
DECLARE_FLOAT(tzz64);
DECLARE_FLOAT(tzz65);
DECLARE_FLOAT(tzz66);
DECLARE_FLOAT(tzz67);
DECLARE_FLOAT(tzz68);
DECLARE_FLOAT(tzz69);


#endif
