#if USE_EXPLICIT_DECLARES
// declare variables
DECLARE_FLOAT(dhx1x1);
DECLARE_FLOAT(dhy1y1);
DECLARE_FLOAT(dhz1z1);
DECLARE_FLOAT(Energy);
DECLARE_FLOAT(fx1);
DECLARE_FLOAT(fy1);
DECLARE_FLOAT(fz1);
DECLARE_FLOAT(gx1);
DECLARE_FLOAT(gy1);
DECLARE_FLOAT(gz1);
DECLARE_FLOAT(ohx1y1);
DECLARE_FLOAT(ohx1z1);
DECLARE_FLOAT(ohy1z1);
DECLARE_FLOAT(OozpDeviation);
DECLARE_FLOAT(tx5);
DECLARE_FLOAT(tx6);
DECLARE_FLOAT(tx7);
DECLARE_FLOAT(tx8);


#endif
