#if USE_EXPLICIT_DECLARES
// declare variables
DECLARE_FLOAT(AnchorDeviation);
DECLARE_FLOAT(dhx1x1);
DECLARE_FLOAT(dhy1y1);
DECLARE_FLOAT(dhz1z1);
DECLARE_FLOAT(Energy);
DECLARE_FLOAT(fx1);
DECLARE_FLOAT(fy1);
DECLARE_FLOAT(fz1);
DECLARE_FLOAT(gx1);
DECLARE_FLOAT(gy1);
DECLARE_FLOAT(gz1);
DECLARE_FLOAT(ohx1y1);
DECLARE_FLOAT(ohx1z1);
DECLARE_FLOAT(ohy1z1);
DECLARE_FLOAT(tx10);
DECLARE_FLOAT(tx11);
DECLARE_FLOAT(tx12);
DECLARE_FLOAT(tx13);
DECLARE_FLOAT(tx14);
DECLARE_FLOAT(tx15);
DECLARE_FLOAT(tx16);
DECLARE_FLOAT(tx17);
DECLARE_FLOAT(tx18);


#endif
