

def build(bld):
    lisp_source = bld.path.ant_glob("**/*.l* **/*.asd")
    print("In extensions/cando/src/lisp bld.path = %s" % bld.path)
    bld.install_files('${PREFIX}/lib/clasp/extensions/cando/src/lisp/',lisp_source,relative_trick=True,cwd=bld.path)
