(load "source-dir:extensions;cando;src;lisp;start-cando.lisp")
(in-package :cando-user)
*default-pathname-defaults*

(require :asdf)
(asdf:load-asd (merge-pathnames "~/Development/ti-run/src/ti-run.asd"))
(ql:quickload :ti-run)
(leap.core::clear-path)
(add-path "amber:dat;leap;prep;")
(add-path "amber:dat;leap;lib;")
(add-path "amber:dat;leap;parm;")
(add-path "amber:dat;leap;cmd;")
(add-path "amber:dat;antechamber;")
(source "leaprc.protein.ff14SB")
(:= *ti-runs* (make-instance 'ti-run:calculation))
*ti-runs*
(:= *tests* (list (cons :c1 (lambda (a) (eq (chem:get-name a) :c1)))
                  (cons :c3 (lambda (a) (eq (chem:get-name a) :c3)))
                  (cons :c5 (lambda (a) (eq (chem:get-name a) :c5)))))
(:= *pick* (chem:compile-smarts 
             "[C:6]1~[C<c1>:1]~C~[C<c3>:3]~C~[C<c5>:5]~C1" :tests *tests*))
(:= *sk* (handler-bind ((warning #'muffle-warning))
             (with-open-file (fin (open "ligands.cdxml" :direction :input))
             (chem:make-chem-draw fin :add-hydrogens nil))))
(ti-run:setup-ligands *ti-runs* *sk*)
(:= *lysozyme* (load-pdb "181L_mod.pdb"))
(pushnew *lysozyme* (ti-run:receptors *ti-runs*))
(directory "*.*")
(load-off (merge-pathnames "phen.lib"))
(load-off (merge-pathnames "benz.lib"))
(:= *ligs* (load-pdb "bnz_phn.pdb"))
*pick*
(alexandria:hash-table-alist (ti-run::pattern-atoms *pick* *ligs*))
(clear-force-field)
(load-atom-type-rules "ATOMTYPE_GFF.DEF")
(load-amber-params "gaff.dat")
(ti-run:build-ligands *ti-runs*)
(show (ti-run:layout-ligands *ti-runs* :accessor 'ti-run::molecule))
(ti-run::pose-ligands-using-pattern *ti-runs* *pick* *ligs*)
