

def build(bld):
    lisp_source = bld.path.ant_glob("**/*")
    print("In extensions/cando/src/data bld.path = %s" % bld.path)
    bld.install_files('${PREFIX}/lib/clasp/source-code/extensions/cando/src/data/',lisp_source,relative_trick=True,cwd=bld.path)
