name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt install -y binutils-gold libbsd-dev clang-14 libclang-14-dev llvm-14 llvm-14-dev libelf-dev libgmp-dev libncurses-dev libunwind-dev ninja-build sbcl zlib1g-dev libnetcdf-dev libexpat1-dev libfmt-dev libboost-all-dev

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost fmt gmp llvm@13 ninja pkg-config sbcl ecl netcdf zeromq

    - name: Checkout clasp
      uses: actions/checkout@v3
      with:
        repository: clasp-developers/clasp
        ref: main

    - name: Checkout cando
      uses: actions/checkout@v3
      with:
        path: extensions/cando

    - uses: conda-incubator/setup-miniconda@v2

    - name: Install AmberTools
      run: |
        conda install -c conda-forge ambertools

    - name: Build Clasp (koga/Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        ./koga --no-clang-cpp --ldlibs=-ldl --extensions=cando,seqan-clasp --skip-sync=cando

    - name: Build Clasp (koga/MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        ./koga --extensions=cando,seqan-clasp --skip-sync=cando

    - name: Build Clasp (ninja)
      run: |
        ninja -C build

    - name: Run regression tests
      run: |
        ninja -C build test

    - name: Run Cando regression tests
      run: |
        ninja -C build cando-test
